sudo: required
language: java
dist: trusty
jdk:
- oraclejdk8
notifications:
  email: false
script:
  - ls -al
  - curl https://api.github.com/repos/gama-platform/gama/releases
  - npm -help
branches:
  only:
  - master
