# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ci
    - run: npm install --save xmlhttprequest
    - run: node updateData.js
    - run: git config --global user.email "benoit.gaudou@gmail.com"
    - run: git config --global user.name "Louis-Lcq"
    - run: git config --global push.default simple
    - run: git status
    - run: git remote rm origin
    - run: git remote add origin https://Louis-Lcq:$GH_token_public_repo@github.com/Louis-Lcq/testGitHubAPI.git
    - run: git pull origin master
    - run: git commit ./docs/assets/data/* --message "update data" 
    - run: git status
    - run: git push origin master
